### ISSUE TITLE
Best practices for packing (dockerizing) Java/Kotlin apps

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cybernode-archive#122]
Article from RedHat shows that Java/Kotlin memory usage should artificially limited to be effective inside containers - https://developers.redhat.com/blog/2017/03/14/java-inside-docker/

At the very least options `-XX:+PrintFlagsFinal -XX:+PrintGCDetails` should be specified to debug what Java is up to.

**Comment by cyborgshead** [comment]
Issue moved to [cyberFund/cybernode #3](https://github.com/cyberFund/cybernode/issues/3) via [**ZenHub**](https://www.zenhub.com/)
