### ISSUE TITLE
Document CI/CD guidelines

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cybernode-archive#123]
Checklist for CI/CD setup for container delivery:

* [ ] each `master` commit builds `:nightly`
  * [x] cyber-search
  * [ ] cyber-markets
  * [ ] cyber-ui
* [ ] each tag commit builds `:latest` and versioned container

---

* [ ] Maintain mapping between repositories and docker containers
  * [ ] cyber-search
  * [ ] cyber-markets
  * [ ] cyber-ui

**Comment by cyborgshead** [comment]
Issue moved to [cyberFund/cybernode #2](https://github.com/cyberFund/cybernode/issues/2) via [**ZenHub**](https://www.zenhub.com/)
