### ISSUE TITLE
Check way to use crossbar.io for microservice communication

### ISSUE THREAD

**Issue by cyborgshead** [cyberFund/cybernode-archive#21]
[-> crossbar.io](http://crossbar.io/)

**Comment by cyborgshead** [comment]
Also to discuss about microservices:
[microservices-dashboard](https://github.com/ordina-jworks/microservices-dashboard)

[awesome-microservices](https://github.com/mfornos/awesome-microservices)

[micro](https://github.com/micro/micro)

**Comment by cyborgshead** [comment]
http://senecajs.org/

http://feathersjs.com/

**Comment by cyborgshead** [comment]
@nxtpool http://crossbar.io/docs/Getting-started-with-NodeJS/

**Comment by abitrolly** [comment]
At the current phase of cybernode evolution, it doesn't operate on microservice levels. Our stack currently uses kubernetes for component management to make sure components are connected, and 

It most likely change in future as we may need a better control over component lifecycle to detect deadlocks, misconfiguration and communication problems, so I leave [stack option](https://github.com/cyberFund/cybernode/labels/stack%20option) here for further investigation.
