### ISSUE TITLE
Setup ElasticSearch with Kubernetes

### ISSUE THREAD

**Issue by cyborgshead** [cyberFund/cybernode-archive#38]
Need to setup ElasticSearch instances (with replication) in cluster (in different machines) with Kubernetes and write documentation to this process

**Comment by abitrolly** [comment]
Security notes - https://www.elastic.co/blog/found-elasticsearch-security

> Unlike most other databases, however, Elasticsearch has a feature allowing arbitrary code execution.

> Elasticsearch has no concept of a user. Essentially, anyone that can send arbitrary requests to your cluster is a “super user”.

**Comment by abitrolly** [comment]
Needs at least `vm.max_map_count=262144` for Docker in production mode - https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode - see also https://stackoverflow.com/questions/11683850/how-much-memory-could-vm-use

**Comment by abitrolly** [comment]
Moved to https://github.com/cyberFund/cyber-search
