### ISSUE TITLE
Full node Bitcoin

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cybernode-archive#39]
#36 is the parent issue.

Bitcoin full node implementations:

1. Bitcoin Core (native) - https://bitcoin.org/en/full-node - Satoshi:0.14.1
2. Bitcore - https://bitcore.io/ - Satoshi:0.11.2(bitcore) ([132 nodes](https://bitnodes.21.co/nodes/?q=bitcore))
3. Bitcoin in Go - https://github.com/btcsuite/btcd - ([22 nodes](https://bitnodes.21.co/nodes/?q=btcd))

Requirements [from bitcoin.org](https://bitcoin.org/en/full-node):

1. 125 GB disk space
2. 2 GB of RAM
3. 400 kilobits (50 kilobytes) upload speed
4. 200+ GB/month upload
5. 20+ GB/month download
6. Min 6 hours/day uptime

Optional user level config:
1. set upload/download limits
2. turn off low-power mode that slows or halts network traffic (defaults for laptops and OS X user hardware) while full node is running

ToDo:
* [x] provide actual requirements through monitoring reports (will solve when monitoring is up)

What other problems are expected?
What optimizations should be applied?
What enhancements to the full node we need?

**Comment by abitrolly** [comment]
Bitcore runs patched native client (Bitcoin Core), but it stuck at Satoshi:0.12.1(bitcore). [Bitcore User-Agents](https://bitnodes.21.co/nodes/?q=bitcore).

[Bitcore site](https://bitcore.io/) says:
> For wallet application development, additional indexes have been added into Bitcoin for querying address balances, transaction history, and unspent outputs.

Do we use them? Where are tests for the functionality that we need? Because if we stick to Bitcore, we will miss all changes for versions 13.0+ - https://bitcoin.org/en/version-history

**Comment by abitrolly** [comment]
`btcd` looks like it stuck at 0.12.x too - https://github.com/btcsuite/btcd/milestone/1 - but it implements cool idea of [separation between chain and wallet](https://blog.conformal.com/btcd-not-your-moms-bitcoin-daemon/).

**Comment by abitrolly** [comment]
Update on `btcd` architecture - https://github.com/btcsuite/btcd/issues/951 - looks pretty generic for just any blockchain database. Would be really interesting to compare its performance to `bitcore`, which is our current choice for some undocumented reasons.

**Comment by abitrolly** [comment]
From discussion in #36, `bitcore` speed is unsatisfying for us now,

**Comment by cyborgshead** [comment]
@abitrolly is there api for btcd like https://github.com/bitpay/insight-api for bitcore?

**Comment by abitrolly** [comment]
The API is pretty extensive - https://github.com/btcsuite/btcd/blob/master/docs/json_rpc_api.md
I need API tests to understand what exact commands/outputs are needed.

**Comment by abitrolly** [comment]
Full node Bitcoin is running on `btcd` - https://bitnodes.21.co/nodes/83.219.158.73-8333/ 😁
