### ISSUE TITLE
Add simple webadmin for node, index and resource management

### ISSUE THREAD

**Issue by mastercyb** [cyberFund/cybernode-archive#4]
My vision is something like [that](https://docs.google.com/spreadsheets/d/1XLbNMbCQnLO1xEtWwQpYb2wCi4_jmrk_-IRuCqDALKI/edit?usp=sharing)
<img width="1177" alt="screen shot 2017-01-04 at 21 20 40" src="https://cloud.githubusercontent.com/assets/410789/21643555/e358309c-d2c3-11e6-93fa-c82328b749e9.png">

**Comment by nxtpool** [comment]
Implemented http://state.cybernode.cyber.fund

**Comment by cyborgshead** [comment]
@nxtpool this is done, basic panel already implemented

**Comment by cyborgshead** [comment]
first ideas..
cybernode help
cybernode update
cybernode upgrade
cybernode init (cybernode ID)
cybernode state
cybernode about
cybernode ui

cybernode chains list 
cybernode chains up all
cybernode chains up bitcoin
cybernode chains stop bitcoin
cybernode chains remove bitcoin

cybernode chains indexing up
cybernode chains indexing stop

cybernode browser up
cybernode browser stop

cybernode markets list
cybernode markets up all
cybernode markets up etherdelta

cybernode markets processing up
cybernode markets processing stop 

cybernode nodes ipfs up
cybernode nodes ipfs stop

browser, chaingear, chains, ellasandra, kafka, markets, search, api

**Comment by cyborgshead** [comment]
would like to try Go or JS to develop CLI for cybernode
https://github.com/urfave/cli
https://github.com/tj/commander.js/
