### ISSUE TITLE
Fix storage location

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cybernode-archive#55]
* [x] btcd writes directly to `~/cyberdata` - should be `~/cyberdata/btcd`
* [x] rethinkdb instance writes to default volume directly - should be `~/cyberdata/rethink`

Related to #54 - Mars got big HDD and 512Gb SSD. Figure out which data should go to SSD to avoid bottlenecks. Figure out the canonical way to measure bottlenecks.

**Comment by abitrolly** [comment]
`btcd` storage location is fixed in #56.

**Comment by cyborgshead** [comment]
@abitrolly there are 4 4TB HDD disks , sdd/sdb/sdc/sda , let's move cyberdata to one of this volumes
<img width="349" alt="screenshot 2017-06-21 20 34 05" src="https://user-images.githubusercontent.com/1690657/27400670-1bcbc822-56c1-11e7-8cb4-5dcbec45580d.png">
need to format them before

**Comment by abitrolly** [comment]
@litvintech I thought for some reason that they are connected into RAID. Which command do you use to produce such beautiful tree?

**Comment by cyborgshead** [comment]
@abitrolly lsblk -o NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL

**Comment by cyborgshead** [comment]
@abitrolly they are not connected in raid

**Comment by abitrolly** [comment]
`crawler` writes to disk at 4k/sec, but disk space used is 558Mb over 100sec, which is 5Mb/sec. Somewhat strange.

![clipcrop](https://user-images.githubusercontent.com/8781107/27419394-5d5ffe08-5729-11e7-9931-77eff7734ef7.png)

**Comment by cyborgshead** [comment]
@abitrolly very strange, going to check this for myself

**Comment by abitrolly** [comment]
```
cgdisk /dev/sda
mkfs -t ext4 -L cyberdata /dev/sda1
```
```
# lsblk -o NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL
NAME        FSTYPE     SIZE MOUNTPOINT      LABEL
loop1       squashfs  79,5M /snap/core/1689
sdd                    3,7T
sdb                    3,7T
loop0       squashfs   3,5M /snap/micro/1
sdc                    3,7T
sda                    3,7T
└─sda1      ext4       3,7T                 cyberdata
nvme0n1              465,8G
├─nvme0n1p3 swap        64G [SWAP]
├─nvme0n1p1 vfat       512M /boot/efi
└─nvme0n1p2 ext4     401,3G /
```
Now need to mount it automatically on boot to `/home/cyber/cyberdata`.

**Comment by abitrolly** [comment]
HDD mountpoint relocation is now tracked in #61.

Let's get back to RethinkDB issue when we get `crawler` up and running.
