### ISSUE TITLE
Markets failed to pack

### ISSUE THREAD

**Issue by abitrolly** [cyberFund/cybernode-archive#87]
https://travis-ci.org/cyberFund/cybernode/builds/265594619#L1793
```
./project-build.sh: line 20: cd: build/libs: No such file or directory

The command '/bin/sh -c ./project-build.sh' returned a non-zero code: 1
```

**Comment by abitrolly** [comment]
@hleb-albau where did binaries move from `build/libs`?

**Comment by hleb-albau** [comment]
@abitrolly What you want to do here?

**Comment by hleb-albau** [comment]
@abitrolly by the way 
https://github.com/cyberFund/cyber-markets/blob/development/.circleci/config.yml

**Comment by abitrolly** [comment]
@hleb-albau here we host two types of scripts for every `cybernode` component (that we may need to customize) - one for building "customized" `cyber-markets` app image and another to run it.

When I need to test various component combinations of `cybernode` manually, I need not to be dependent on CircleCI. It is like Linux packaging, but for `cybernode`.

I will extract the app from CircleCI script then.

**Comment by abitrolly** [comment]
No time for restoring `cyber-market` builds in `cybernode`. Builds are moved to CircleCI, need to add sanity tests that images are working to close this ticket.

@hleb-albau how can I check quickly that images are fine? For `btcd` I just run image with `--version` argument - would be nice to get some diagnostic command lines for `cyber-markets` components too. It should just run and exit itself without error.

**Comment by abitrolly** [comment]
CI/CD loop is being redesigned for all cyberFund projects separately from `cybernode` for now. Markets are being packed externally and this process is not part of `cybernode` testing. `cybernode` may be able to rebuild external component in future (self-healing).
